<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact Form Submission</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            background-color: #fff;
            padding: 20px;
            margin: 20px auto;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 600px;
        }
        .header {
            background-color: #004080;
            color: #ffffff;
            padding: 10px;
            border-radius: 8px 8px 0 0;
            text-align: center;
        }
        .content {
            padding: 20px;
        }
        .content p {
            font-size: 16px;
            line-height: 1.6;
            color: #333;
        }
        .footer {
            background-color: #f4f4f4;
            padding: 10px;
            border-radius: 0 0 8px 8px;
            text-align: center;
            font-size: 14px;
            color: #666;
        }
        .contact-details {
            margin-top: 20px;
        }
        .contact-details p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Contact Form Submission</h1>
        </div>
        <div class="content">
            <p>Dear Admin,</p>
            <p>You have received a new contact form submission. Here are the details:</p>
            <div class="contact-details">
                <p><strong>Name:</strong> {{$data['name']}}</p>
                <p><strong>Email:</strong> {{$data['email']}}</p>
                <p><strong>Contact Number:</strong> {{$data['phoneNumber']}}</p>
                <p><strong>Message:</strong></p>
                <p>{{$data['message']}}</p>
            </div>
        </div>
        <div class="footer">
            <p>This email was generated by Builders Bridge System. Please do not reply to this email.</p>
        </div>
    </div>
</body>
</html>
